export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  USER = 'USER',
}

export enum ModulesAllowed {
  PRODUCT = 'PRODUCT',
  EMPLOYEE = 'EMPLOYEE',
  CUSTOMER = 'CUSTOMER',
  ORDER = 'ORDER',
  CATEGORY = 'CATEGORY',
  CART = 'CART',
  PAYMENT = 'PAYMENT',
  SHIPPING = 'SHIPPING',
  ADDRESS = 'ADDRESS',
  COUPON = 'COUPON',
  REVIEW = 'REVIEW',
  WISHLIST = 'WISHLIST',
  ORDER_STATUS = 'ORDER_STATUS',
  ORDER_DETAIL = 'ORDER_DETAIL',
}
